/*
 * This source file was generated by the Gradle 'init' task
 */
package wisesaying_tdd;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayOutputStream;
import java.util.Scanner;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import wisesaying_tdd.wisesaying.Util.TestUtil;

public class AppTest {
    public String output = "";

    @Test
    @DisplayName("초기 화면 표시")
    public void DisplayInit() {
        output = AppTest.run("");
        assertThat(output).contains("== 명언 앱 ==");
    }

    @Test
    @DisplayName("명령 ) 표시")
    public void DisplayCommand() {
        output = AppTest.run("");
        assertThat(output).contains("명령 ) ");
    }

    @Test
    @DisplayName("명령 ) 의 복수건 출력")
    public void DisplayCommands() {
        output = AppTest.run("""
                점프
                점프
                """);
        String[] sArr = output.split("명령 \\) "); 
        assertThat(sArr).hasSize(4);
    }

    public static String run(String input) {
        input = input.stripIndent().trim() + "\n 종료";
        Scanner sc = TestUtil.genScanner(input);
        ByteArrayOutputStream outputStream = TestUtil.setOutToByteArray();

        App app = new App(sc);
        app.run();

        String output = outputStream.toString();

        TestUtil.clearSetOutToByteArray(outputStream);

        return output;
    }
}
