/*
 * This source file was generated by the Gradle 'init' task
 */
package wisesaying_tdd;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        WiseSayingTest wt = new WiseSayingTest();

        //wt.AddWiseSaying();
    }
}
